# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: pip3 install -r requirements.txt # runs during prebuild
    command: pytest -v

vscode:
  extensions:
    - almenon.arepl
    - littlefoxteam.vscode-python-test-adapter
    - hbenl.vscode-test-explorer
    - hbenl.test-adapter-converter
